spring:
  application:
    name: kafka-messagepack-stub
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      # Требование задачи: SASL/PLAIN без SSL
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN

app:
  kafka:
    username: kafka-user
    password: kafka-password
    # Можно оставить пустым, тогда строка соберется автоматически из username/password
    jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-user" password="kafka-password";
    # Простой rate-limit producer (Thread.sleep)
    rate-limit-ms: 200
    group-ids:
      group1: group-1
      group2: group-2
    topics:
      topic1-input: topic-1
      topic2-output: topic-2
      topic3-input: topic-3
      topic4-output: topic-4
  templates:
    path: templates
    # По задаче: 2 исходных шаблона (вложенные списки), которые преобразуются в MessagePack бинарник
    files:
      - template-flow-1.yaml
      - template-flow-2.yaml

logging:
  level:
    root: INFO
    com.example.kafkastub: INFO
